// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// user
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const SIGN_USER_IN_SUCCESS = 'SIGN_USER_IN_SUCCESS';
export const SIGN_USER_IN_FAIL = 'SIGN_USER_IN_FAIL';

// profile
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

// search history
export const FETCH_SEARCH_HISTORY_SUCCESS = 'FETCH_SEARCH_HISTORY_SUCCESS';
export const FETCH_SEARCH_HISTORY_FAIL = 'FETCH_SEARCH_HISTORY_FAIL';
export const SAVE_SEARCH_SUCCESS = 'SAVE_SEARCH_SUCCESS';
export const SAVE_SEARCH_FAIL = 'SAVE_SEARCH_FAIL';

// search
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS';
export const SEARCH_LOCATION_FAIL = 'SEARCH_LOCATION_FAIL';
export const DISPLAY_RESULTS_SUCCESS = 'DISPLAY_RESULTS_SUCCESS';
export const DISPLAY_RESULTS_FAIL = 'DISPLAY_RESULTS_FAIL';

// buildings
export const ADD_BUILDING_SUCCESS = 'ADD_BUILDING_SUCCESS';
export const ADD_BUILDING_FAIL = 'ADD_BUILDING_FAIL';
export const UNADD_BUILDING_SUCCESS = 'UNADD_BUILDING_SUCCESS';
export const UNADD_BUILDING_FAIL = 'UNADD_BUILDING_FAIL';
export const ADD_UNIT_SUCCESS = 'ADD_UNIT_SUCCESS';
export const ADD_UNIT_FAIL = 'ADD_UNIT_FAIL';
export const UNADD_UNIT_SUCCESS = 'UNADD_UNIT_SUCCESS';
export const UNADD_UNIT_FAIL = 'UNADD_UNIT_FAIL';
